### ISSUE TITLE
objects within definitions are not shown properly in the docs

### ISSUE THREAD

**Issue by lea-anthony** [sourcey/spectacle#98] opened 2017-10-17 06:50 UTC
Problem:
When a definition has a property that is an object, this property is shown as "object" with none of its own properties outputted to the doc.

Example doc fragment:
```
...
      challenges:
        type: object
        properties:
          total:
            description: Total number of challenges
            type: integer
          completed:
            description: Number of challenges completed by participant
            type: integer
...
```
Renders to:
challenges: object

Expected behaviour:

Sub-properties to be documented also.

**Comment by yyamano** [comment] 2017-12-04 14:52
@lea-anthony It works fine to me. Could you send a full doc that reproduces the issue to me?

**Comment by yyamano** [comment] 2018-01-30 13:23
@puranjay6 The latest version of spectacle with https://github.com/yyamano/spectacle/blob/issue-98/test/fixtures/issue-98.yml works for me. I might misunderstand the issue. Could you upload your  OpenAPI spec file?

**Comment by puranjay6** [comment] 2018-01-30 17:17
@yyamano i am attaching my swagger.json file. 
[swagger.json.zip](https://github.com/sourcey/spectacle/files/1678647/swagger.json.zip)

For eg, I have defined a schema like this
	swagger_schema :StageValue do
		property :stage do
			key :description, 'Give a description of all the parameters'
			property :id do
				key :type, :integer
				key :format, :int64
			end
			property :stage_type do
				key :type, :string
			end
			property :name do
				key :type, :string
			end
			property :num_cycles do
				key :type, :integer
				key :format, :int32
			end
			property :auto_delta do
				key :type, :boolean
				key :default, false
			end
			property :auto_delta_start_cycle do
				key :type, :integer
			end
		end

Now in the schema definition this is displayed: 

stage: object
Give a description of all the parameters

But the other properties which i defined inside stage dont get displayed 
![screen shot 2018-01-30 at 9 17 02 am](https://user-images.githubusercontent.com/10890269/35580606-5c13d0f0-059e-11e8-88af-3737b2cad34c.png)

**Comment by puranjay6** [comment] 2018-01-31 18:41
hey @yyamano is it not like this for you ? 
@lea-anthony were you able to get it working ?

**Comment by yyamano** [comment] 2018-02-01 04:42
@puranjay6 Thank you, I understood the issue. 

spectacle currently doesn't support it. With my modification at https://github.com/yyamano/spectacle/commit/17573051d6be02f2a05b2792a8f7ae349dfc7979 , the nested properties get displayed as below. The change is just a POC. We need to improve display format.

![sc](https://user-images.githubusercontent.com/108492/35661460-aaf582fa-0755-11e8-87d8-ac645c1a3d09.png)

**Comment by puranjay6** [comment] 2018-02-01 04:49
@yyamano how can i get your change ?

**Comment by yyamano** [comment] 2018-02-01 05:07
@puranjay6 You have to patch the source code on your dev box by hand.

**Comment by puranjay6** [comment] 2018-02-01 05:08
@yyamano So i fork the repo and make the change you made on my side and then use that to build ?

**Comment by yyamano** [comment] 2018-02-01 06:02
@puranjay6 Yap.

**Comment by auscaster** [comment] 2018-03-20 10:18
Can we close this one off now that @yyamano 's branch has been merged upstream?

**Comment by yyamano** [comment] 2018-04-06 09:33
@auscaster I don't think it's merged into the master. I feel it's a bit ugly. If you are OK with it, I will send a pull request.

**Comment by noliran** [comment] 2018-04-12 17:33
Hi @yyamano,
Changing your snippet to:
```
      {{#if properties}}
        <dt class="json-inner-schema">
          {{~>json-schema/body $ref="" description=""}}
        </dt>
      {{/if}}
      {{#if items}}
        <dt class="json-inner-schema">
          {{~>json-schema/body $ref="" description=""}}
        </dt>
      {{/if}}
```

Makes it much clearer (and also adds support for arrays along the way). What do you think?

**Comment by yyamano** [comment] 2018-04-13 07:26
@noliran Looks great!

![screenshot](https://user-images.githubusercontent.com/108492/38721991-6053d908-3f37-11e8-8045-92819530fd00.png)

**Comment by auscaster** [comment] 2018-04-15 16:15
Awesome work guys! I'm merging the PR now

**Closed** 2018-04-15 16:16 UTC
