### ISSUE TITLE
How to generate a query request sample

### ISSUE THREAD

**Issue by chook** [sourcey/spectacle#120] opened 2018-02-10 02:00 UTC
I'm trying to understand what's the best way to get the query parameters as a request example.
From the looks of it, it seems only **body** is supported, and not query.

Also - is there a way to force a CURL sample for requests?

**Comment by auscaster** [comment] 2018-03-20 10:37
Request query parameters are indeed supported.

Currently there is no CURL sample for requests, but I would be open to a PR for this. I'll close this off for now since this functionality is a duplicate of #70

**Closed by auscaster** 2018-03-20 10:37 UTC

**Comment by chook** [comment] 2018-04-15 13:43
Hi @auscaster - is there any way of supplying a default request sample? Something that will show the readers what a valid URL could look like?
